name: Nix

on:
  workflow_call:
    inputs:
      command:
        required: true
        type: string

jobs:
  nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
        with:
          install_url: https://nixos.org/nix/install
          extra_nix_config: |
            auto-optimise-store = true
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            experimental-features = nix-command flakes
      - uses: cachix/cachix-action@v12
        with:
          name: nix-gaming
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: ${{ inputs.command }}
