name: Nix

on:
  workflow_call:
    inputs:
      command:
        required: true
        type: string
    secrets:
      CACHIX_AUTH_TOKEN:
        required: false

jobs:
  nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: cachix/cachix-action@v15
        with:
          name: nix-gaming
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: ${{ inputs.command }}
